version: '3'
services:

  app:
    build: ./app
    container_name: battleship-app
    links:
      - mongodb
    networks:
      - back

  watchdog:
    build: ./watchdog
    container_name: battleship-watchdog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back
    depends_on:
      - app

  mongodb:
    image: mongo:3.6
    container_name: battleship-mongodb
    networks:
      - back

  nginx:
    image: nginx:1
    container_name: battleship-nginx
    # ports:
    #   - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
      - watchdog
    networks:
      - back

networks:
  back:
    driver: bridge
