version: '3'
services:

  app:
    build: .
    # links:
    #   - mongodb

  # mongodb:
  #   image: node:10
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: app
  #     MONGO_INITDB_ROOT_PASSWORD: app
    
  nginx:
    image: nginx:1
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  #     - mongodb
